<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Helper\" />
      <Folder Include="Libs\" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="halcondotnet">
        <HintPath>Libs\Halcon\halcondotnet.dll</HintPath>
      </Reference>
      <Reference Include="MvCameraControl.Net">
        <HintPath>C:\Program Files (x86)\MVS\Development\DotNet\win64\netstandard2.0\MvCameraControl.Net.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Commons\Commons.csproj" />
    </ItemGroup>

</Project>
